/** Shared motion timing — no imports; safe for state + motion layers. */
export const TIMING = {
  ease: 'cubic-bezier(.32,.94,.35,1)',
  /* Filter feel — quieter ease-out; not the project-open spring. */
  filterEase: 'cubic-bezier(.33,0,.15,1)',
  flip: 380,
  view: 420,
  filterLeave: 120,
  filterFlip: 240,
  filterFlipMax: 300,
  filterEnter: 130,
  filterEnterIndex: 100,
  /* Sector→Sector: content handoff inside a stable slot (not whole-field fade). */
  slotOut: 100,
  slotIn: 120,
  slotHandoffFloor: 0.15,
  /* Sector→All return: local FLIP only; remote resolves without travel. */
  filterReturnMicro: 20,
  filterReturnLocal: 280,
  filterReturnViewPad: 48,
  /* All↔Sector FLIP band still used by Sector→All local continuity only. */
  filterMoveMin: 16,
  filterMoveMax: 760,
  filterMoveCap: 0,
  /* All→Sector: one universal upward SECTOR_SETTLE (no source-distance FLIP). */
  sectorSettleY: 40,
  sectorSettleYMobile: 24,
  sectorSettleOp: 0.28,
  sectorSettle: 260,
  sectorLeaveOverlap: 56,
  open: 430,
  closeFade: 180,
  close: 400,
  lateralFade: 160,
  lateral: 360,
  depth: 150,
  ideaRestore: 420,
  infoThen: 200,
  intro: 1700,
  introHold: 200,
  introVideoFade: 420,
  introFlight: 560,
  introSwipe: 620,
  introChrome: 220, /* after breath — ~300ms from click */
  introWorld: 0,
  introBreath: 80,
  brandDelay: 250,
  viewAfterClose: 650,
  hashDepth: 0,
  watchdog: 1500,
};
